import { generateManifest } from '../main-pipeline/manifestGenerator.mjs';
import { signManifest } from '../main-pipeline/signingLayer.mjs';
import { embedManifest } from '../main-pipeline/embeddingLayer.mjs';
import { extractManifest } from 'c2pa-text';
import { decompress, decodeFromCBOR } from '../main-pipeline/compression.mjs';
import assert from 'node:assert/strict';
/*
 * [I.1] WHAT THIS FILE DOES
 * This test runs Stages 1, 2, and 3 in sequence — the full build side
 * of the pipeline — then immediately reverses the last step to confirm
 * the manifest survived embedding intact.
 * It is the first test that proves the invisible signal actually works:
 * that the text looks unchanged, that the binary payload is recoverable,
 * and that the recovered payload decompresses back into the full signed manifest.
 * Three checks. Each one builds on the previous. All three must pass.
 */

/*
 * [I.2] THE TEST TEXT
 * A real sentence rather than repeated characters.
 * This matters for embedding — the c2pa-text library attaches invisible
 * Unicode characters to real text structure. Using a realistic string
 * confirms the embedding method behaves correctly on actual content,
 * not just on synthetic input.
 * The boundary between segments sits at offset 44 — end of the first sentence.
 * Everything from 45 onward is ai_generated.
 */

const visibleText = "This is a test sentence written by a human. The rest was generated by AI to demonstrate the embedding layer working correctly across a longer piece of content.";

/*
 * [I.3] BUILDING THE MANIFEST — STAGE 1
 * generateManifest() runs exactly as it would in production.
 * Two segments: human (0–44) and ai_generated (45–end).
 * new Date().toISOString() produces a live timestamp — unlike test/testManifest.mjs
 * which used a fixed date, this test uses the actual current time.
 * The text hash produced here will be unique to this exact visibleText string.
 */
const contentSignedAt = '2026-08-02T00:00:00.000Z';
const manifest = generateManifest({
  visibleText,
  segments: [
  {
    segmentId: 's001',
    startOffset: 0,
    endOffset: 43,
    origin: 'human',
    confidence: 0.95,
  },
  {
    segmentId: 's002',
    startOffset: 44,
    endOffset: visibleText.length - 1,
    origin: 'ai_generated',
    aiTool: 'claude-sonnet-4',
    confidence: 0.98,
  },
  ],
  signingTool: "lps-reference-implementation-v0.1",
  contentSignedAt: contentSignedAt
});

assert.equal(manifest.content_signed_at, contentSignedAt);
assert.equal(Object.hasOwn(manifest, 'signed_at'), false);
assert.equal(
  manifest.text_length,
  Buffer.byteLength(visibleText.replace(/[\r\n ]+$/, ''), 'utf8')
);

/*
 * [I.4] SIGNING AND EMBEDDING — STAGES 2 AND 3
 * signManifest() wraps the manifest in a cryptographic signature.
 * embedManifest() compresses it, encodes it to binary, and hides it
 * inside embeddedText as invisible Unicode characters.
 * embeddedText is the final document — what would be published or distributed.
 * To the human eye it is identical to visibleText. The manifest is inside it.
 */

const signedManifest = signManifest(manifest);
const embeddedText = embedManifest(visibleText, signedManifest);

assert.equal(signedManifest.ev, 1);
assert.equal(signedManifest.manifest.content_signed_at, contentSignedAt);
assert.equal(typeof signedManifest.signed_at, 'string');
assert.ok(signedManifest.signed_at.length > 0);
assert.ok(signedManifest.signature);

/*
 * [I.5] CHECK 1 — VISIBLE TEXT UNCHANGED
 * extractManifest() from c2pa-text scans the embedded text and splits it
 * into two things: cleanText (visible characters only) and manifest (the binary payload).
 * This check compares cleanText against the original visibleText character by character.
 * PASS means the embedding process added nothing visible and removed nothing visible.
 * FAIL means the embedding corrupted or altered the readable content —
 * which would be a critical failure of the entire system.
 */

console.log("--- Step 1: Visible text unchanged? ---");
const extracted = extractManifest(embeddedText);
assert.ok(extracted);
assert.equal(extracted.cleanText, visibleText);

/*
 * [I.6] CHECK 2 — BINARY PAYLOAD RECOVERABLE
 * extracted.manifest is the raw binary buffer pulled out of the embedded text.
 * This check confirms that something was found — that the embedding produced
 * a recoverable payload and extraction did not return null or undefined.
 * This check does not verify the content of the payload yet.
 * It only confirms the signal survived the embed/extract round trip.
 */

console.log("\n--- Step 2: Manifest bytes extracted? ---");
assert.ok(extracted.manifest);

/*
 * [I.7] CHECK 3 — MANIFEST RECOVERABLE FROM BINARY
 * decodeFromCBOR() converts the binary buffer back to the shortcode object.
 * decompress() expands the shortcodes back to the full signed manifest.
 * If either step throws, the payload was corrupted during embedding or extraction.
 *
 * The recovered object is checked for a signature field.
 * A signature present means the full signed manifest came through intact —
 * not just the inner manifest data, but the cryptographic wrapper around it.
 *
 * The summary block below prints four values for visual confirmation:
 *   Algorithm     — should match what main-pipeline/signingLayer.mjs set ("es256").
 *   Signed at     — the ISO timestamp from when signManifest() ran.
 *   Segments      — should be 2, matching the two segments defined above.
 *   Signature present — true confirms the cryptographic seal survived.
 *
 * Plain English: this check proves the full round trip works.
 * The manifest was built, signed, compressed, hidden in text, extracted,
 * decompressed, and decoded — and it came out the other side intact.
 * That is the core claim of the pipeline. This test proves it.
 */

const recovered = decompress(decodeFromCBOR(extracted.manifest));

assert.equal(recovered.ev, 1);
assert.equal(recovered.signed_at, signedManifest.signed_at);
assert.equal(
  recovered.manifest.content_signed_at,
  contentSignedAt
);
assert.equal(recovered.manifest.text_hash, manifest.text_hash);
assert.equal(recovered.manifest.text_length, manifest.text_length);
assert.equal(recovered.manifest.content_segments.length, 2);
assert.ok(recovered.signature);

for (const segment of recovered.manifest.content_segments) {
  assert.equal(segment.confidence_source, 'tool');
}
