import { generateManifest } from './manifestGenerator.mjs';
import { signManifest } from './signingLayer.mjs';
import { embedManifest } from './embeddingLayer.mjs';
import { extractManifest } from 'c2pa-text';
import { decompress, decodeFromCBOR } from './compression.mjs';

/*
 * [I.1] WHAT THIS FILE DOES
 * This test runs Stages 1, 2, and 3 in sequence — the full build side
 * of the pipeline — then immediately reverses the last step to confirm
 * the manifest survived embedding intact.
 * It is the first test that proves the invisible signal actually works:
 * that the text looks unchanged, that the binary payload is recoverable,
 * and that the recovered payload decompresses back into the full signed manifest.
 * Three checks. Each one builds on the previous. All three must pass.
 */

/*
 * [I.2] THE TEST TEXT
 * A real sentence rather than repeated characters.
 * This matters for embedding — the c2pa-text library attaches invisible
 * Unicode characters to real text structure. Using a realistic string
 * confirms the embedding method behaves correctly on actual content,
 * not just on synthetic input.
 * The boundary between segments sits at offset 44 — end of the first sentence.
 * Everything from 45 onward is ai_generated.
 */

const visibleText = "This is a test sentence written by a human. The rest was generated by AI to demonstrate the embedding layer working correctly across a longer piece of content.";

/*
 * [I.3] BUILDING THE MANIFEST — STAGE 1
 * generateManifest() runs exactly as it would in production.
 * Two segments: human (0–44) and ai_generated (45–end).
 * new Date().toISOString() produces a live timestamp — unlike testManifest.mjs
 * which used a fixed date, this test uses the actual current time.
 * The text hash produced here will be unique to this exact visibleText string.
 */

const manifest = generateManifest({
  visibleText,
  segments: [
    {
      segmentId: "s001",
      startOffset: 0,
      endOffset: 44,
      origin: "human",
      confidence: 0.95
    },
    {
      segmentId: "s002",
      startOffset: 45,
      endOffset: visibleText.length - 1,
      // visibleText.length - 1 = the last character index. Offsets are inclusive.
      origin: "ai_generated",
      aiTool: "claude-sonnet-4",
      confidence: 0.98
    }
  ],
  signingTool: "lps-reference-implementation-v0.1",
  signedAt: new Date().toISOString()
});

/*
 * [I.4] SIGNING AND EMBEDDING — STAGES 2 AND 3
 * signManifest() wraps the manifest in a cryptographic signature.
 * embedManifest() compresses it, encodes it to binary, and hides it
 * inside embeddedText as invisible Unicode characters.
 * embeddedText is the final document — what would be published or distributed.
 * To the human eye it is identical to visibleText. The manifest is inside it.
 */

const signedManifest = signManifest(manifest);
const embeddedText = embedManifest(visibleText, signedManifest);

/*
 * [I.5] CHECK 1 — VISIBLE TEXT UNCHANGED
 * extractManifest() from c2pa-text scans the embedded text and splits it
 * into two things: cleanText (visible characters only) and manifest (the binary payload).
 * This check compares cleanText against the original visibleText character by character.
 * PASS means the embedding process added nothing visible and removed nothing visible.
 * FAIL means the embedding corrupted or altered the readable content —
 * which would be a critical failure of the entire system.
 */

console.log("--- Step 1: Visible text unchanged? ---");
const extracted = extractManifest(embeddedText);
console.log(extracted.cleanText === visibleText ? "PASS" : "FAIL");

/*
 * [I.6] CHECK 2 — BINARY PAYLOAD RECOVERABLE
 * extracted.manifest is the raw binary buffer pulled out of the embedded text.
 * This check confirms that something was found — that the embedding produced
 * a recoverable payload and extraction did not return null or undefined.
 * This check does not verify the content of the payload yet.
 * It only confirms the signal survived the embed/extract round trip.
 */

console.log("\n--- Step 2: Manifest bytes extracted? ---");
console.log(extracted.manifest !== null ? "PASS" : "FAIL");

/*
 * [I.7] CHECK 3 — MANIFEST RECOVERABLE FROM BINARY
 * decodeFromCBOR() converts the binary buffer back to the shortcode object.
 * decompress() expands the shortcodes back to the full signed manifest.
 * If either step throws, the payload was corrupted during embedding or extraction.
 *
 * The recovered object is checked for a signature field.
 * A signature present means the full signed manifest came through intact —
 * not just the inner manifest data, but the cryptographic wrapper around it.
 *
 * The summary block below prints four values for visual confirmation:
 *   Algorithm     — should match what signingLayer.mjs set ("es256").
 *   Signed at     — the ISO timestamp from when signManifest() ran.
 *   Segments      — should be 2, matching the two segments defined above.
 *   Signature present — true confirms the cryptographic seal survived.
 *
 * Plain English: this check proves the full round trip works.
 * The manifest was built, signed, compressed, hidden in text, extracted,
 * decompressed, and decoded — and it came out the other side intact.
 * That is the core claim of the pipeline. This test proves it.
 */

console.log("\n--- Step 3: Manifest recoverable from bytes? ---");
try {
  const recovered = decompress(decodeFromCBOR(extracted.manifest));
  console.log(recovered.signature ? "PASS" : "FAIL");
  console.log("\n--- Recovered manifest summary ---");
  console.log("Algorithm:", recovered.algorithm);
  console.log("Signed at:", recovered.signed_at);
  console.log("Segments:", recovered.manifest.content_segments.length);
  console.log("Signature present:", !!recovered.signature);
  // !! converts the signature string to a boolean. Any non-empty string = true.
} catch (err) {
  console.log("FAIL —", err.message);
}