import { generateManifest } from './manifestGenerator.mjs';
import { signManifest } from './signingLayer.mjs';
import { embedManifest } from './embeddingLayer.mjs';
import { extractManifest } from 'c2pa-text';

const visibleText = "This is a test sentence written by a human. The rest was generated by AI to demonstrate the embedding layer working correctly across a longer piece of content.";

const manifest = generateManifest({
  visibleText,
  segments: [
    {
      segmentId: "s001",
      startOffset: 0,
      endOffset: 44,
      origin: "human",
      confidence: 0.95
    },
    {
      segmentId: "s002",
      startOffset: 45,
      endOffset: visibleText.length - 1,
      origin: "ai_generated",
      aiTool: "claude-sonnet-4",
      confidence: 0.98
    }
  ],
  signingTool: "lps-reference-implementation-v0.1",
  signedAt: new Date().toISOString()
});

const signedManifest = signManifest(manifest);
const embeddedText = embedManifest(visibleText, signedManifest);

console.log("--- Step 1: Visible text unchanged? ---");
const extracted = extractManifest(embeddedText);
console.log(extracted.cleanText === visibleText ? "PASS" : "FAIL");

console.log("\n--- Step 2: Manifest bytes extracted? ---");
console.log(extracted.manifest !== null ? "PASS" : "FAIL");

console.log("\n--- Step 3: Manifest recoverable from bytes? ---");
try {
  const recovered = JSON.parse(new TextDecoder().decode(extracted.manifest));
  console.log(recovered.signature ? "PASS" : "FAIL");
  console.log("\n--- Recovered manifest summary ---");
  console.log("Algorithm:", recovered.algorithm);
  console.log("Signed at:", recovered.signed_at);
  console.log("Segments:", recovered.manifest.content_segments.length);
  console.log("Signature present:", !!recovered.signature);
} catch (err) {
  console.log("FAIL —", err.message);
}